resolver: lts-18.5

packages:
  - .

extra-deps:
  - git: https://github.com/ucsd-progsys/liquidhaskell
    commit: 4500b6799eb7eb87cb344ecc2eed122297ed53b7
    subdirs:
      - .
      - liquid-base
      - liquid-prelude
      - liquid-ghc-prim
  - git: https://github.com/ucsd-progsys/liquid-fixpoint
    commit: ce6fe613efcc33a76aac462a2c2033e2b2b61f01


allow-newer: true
